### ISSUE TITLE
If there are more than 20 fish in the inventory

### ISSUE THREAD

**Issue by Reny900** [SoliaRdi/auto-fishing#15]
the dismantle window will just stay there with the bot stuck after the first 20 fish "smantiling"
also, when trying to re-open the dismantle window it will just put 1 item in there and proceed to dismantle it without put more of it in them

**Comment by SoliaRdi** [comment]
Mod dismantle first 20 fishes, then continue fishing. When inventory is full, dismantles next 20 fishes. The real issue is when you riсh max number of Fish Filet, or not enough for crafting baits (i'll try to add some interactions with pets or traveling banker). If you have many fishes before enabling autofishing - just open inventory once(after enabling )

**Comment by SoliaRdi** [comment]
Second possible reason for this issue - incorrect S_RP_COMMIT_DECOMPOSITION_CONTRACT opcode

**Comment by SoliaRdi** [comment]
should be fixed
