### ISSUE TITLE
script not selling

### ISSUE THREAD

**Issue by cybrwolf** [SoliaRdi/auto-fishing#221]
im on NA, 
got all the right OPCODES,
got all the updated DEF
got lastest version of the script
got lastest updated version of Tera Toolbox
got no error or typo error in my .map file
setting are all set correctly it open npc window, put fish in, but dosent sell 
ive been looking everywhere.. for some odd reason.. it dosent apply the C_STORE_COMMIT

anyone had same issue and fixed it ? :S  well.. i just dunno where to look at :S

**Comment by SoliaRdi** [comment]
Can you use packet logger and watch at C_STORE_COMMIT? To see did it sent or what is sends

**Comment by cybrwolf** [comment]
@SoliaRdi i will, soon as i get home, ill lets you know, for now its on hold for 2 days :( ill keep u posted on it.

**Comment by Artligth** [comment]
@SoliaRdi 

It's not about the post, but I would like to ask you a question:

What to do with xp-tome drops? Do they eventually fill the inventory and stop auto-fishing?

This did not happen to me because I always stop before my inventory is full of xp-tome.
But ... if in case I leave away for a long time, there is nothing to do?

**Comment by SoliaRdi** [comment]
if long time = year then yes, auto-fishing will stop. But i dont think you will fishing so long
