### ISSUE TITLE
Dismantling 

### ISSUE THREAD

**Issue by laejon** [SoliaRdi/auto-fishing#29]
It opens the dismantle menu but does not dismantle the fish unless I click the fish into the dismantling list. It also doesn't close the dismantle window to resume fishing.

**Comment by LeandraTS** [comment]
The script is working fine, the problem you are having is the lack of ID codes for dismantling.

What I have done is, I loaded up a character, went through the setup of selecting the bait to craft, then a couple of fish to dismantle, then typed fish save

This created the saved setup file in the saves folder of let-me-fish-master

I then edited the saved file in notepad++

I literally added every ID code in sequence from Tier 1 to Tier 10 and then saved it.
BaF's Tier 11 so hence I didnt add them

It's time consuming but once you got 1 done and saved, can just make a copy for all your characters and doesn't matter what fish you catch it will dismantle them.

And since it doing it itself it will auto close window.

**Comment by SeaPlayerPotato** [comment]
what region u playing?

**Comment by laejon** [comment]
SEA

**Comment by laejon** [comment]
It basically dismantles 20 fishes and gets stuck. doesn't dismantle more and doesn't close the window.

**Comment by SoliaRdi** [comment]
Update protocol.341702.map

**Comment by laejon** [comment]
that fixes it, thanks
