### ISSUE TITLE
all opcode EU / NA 88.4

### ISSUE THREAD

**Issue by PsykoDev** [SoliaRdi/auto-fishing#291]
Na opcode 88.4

C_CAST_FISHING_ROD = 46443
C_END_FISHING_MINIGAME = 61064
C_PUT_WARE_ITEM = 52749
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 62476
C_START_FISHING_MINIGAME = 60116
C_STOP_FISHING = 24197
C_STORE_COMMIT = 27081
C_STORE_SELL_ADD_BASKET = 23100
S_FISHING_BITE = 42528
S_FISHING_CATCH = 36131
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 61485
S_START_FISHING_MINIGAME = 40318
S_STORE_BASKET = 54436

EU opcode 88.4 

C_CAST_FISHING_ROD = 43591
C_END_FISHING_MINIGAME = 22579
C_PUT_WARE_ITEM = 34823
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 62893
C_START_FISHING_MINIGAME = 40739
C_STOP_FISHING = 47872
C_STORE_COMMIT = 43678
C_STORE_SELL_ADD_BASKET = 34507
S_FISHING_BITE = 24212
S_FISHING_CATCH = 42961
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 23731
S_START_FISHING_MINIGAME = 29037
S_STORE_BASKET = 50056

**Comment by AntiScrewdriver** [comment]
This is awesome ! thank you !

**Comment by fisherman1717** [comment]
thank you, have been waiting for this!

**Comment by kasparov91** [comment]
I have problem when write fish it say me error calli something no auto fish when start it

**Comment by kasparov91** [comment]
I putted this code in map Na tera no work saying error when i write fish

**Comment by PsykoDev** [comment]
node_modules\tera-data\map go here and edit protocol.359881.map with notpasd ++

**Comment by Monstertera** [comment]
Is it safe to fish tho ?

**Comment by AntiScrewdriver** [comment]
> Is it safe to fish tho ?

I would say "riskier than before".

Its not 'really' about weather or not the GMs can detect the mods, because they could always tell.
hell , most of the time, i could tell who's using the fishing mod or not... its more about if they wanna do anything about it.

EU apparently has a thriving player base. And Ban waves are out in full force to protect the sAnCtItY and pUrItY of tHe gAmE !! 

NA on the other hand ... they don't even have a community team. Unless you do something that really shifts the balance, like that pet skill changer not too long ago, they more or less don't care.

Again, that doesn't mean you won't get banned. Can they figure out you're using the fishing mod ? For a lot of the cases, yes. Using these kinda mods has always come with risk. But looks like the risk is higher now, and thats why SoliaRdi decided to put an in-mod warning.

**Comment by SoliaRdi** [comment]
thx

**Comment by kasparov91** [comment]
Tnx lot it work

пет, 27. дец 2019. 11:24 пре подне SoliaRdi <notifications@github.com> је
написао/ла:

**Comment by fisherman1717** [comment]
looks like the latest maintenance for NA made auto fishing not working again.
Anyone has latest opcodes for NA?
